vsphere_user = ""
sphere_password = ""
vsphere_server = ""

data_center = ""
data_store = ""
mgmt_lan = ""
net_adapter_type = ""
guest_id = ""
custom_iso_path = ""
name_new_vm = ""
vm_count = ""
disk_size = ""
num_mem = ""